### ISSUE TITLE
PyPi 2.2.1

### ISSUE THREAD

**Issue by Minkey27** [jazzband/django-axes#198]
My company was looking for a way to disable AccessLog's and I see that that functionality has already been added in 2.2.1. I wanted to test this but 2.2.1 hasn't been uploaded to pypi yet so I can't pip install it.

**Comment by jezdez** [comment]
I've just released 2.3.0 manually to PyPI because Travis PyPI deploy system seems to not take the Jazzband password correctly. Possibly related to https://github.com/travis-ci/dpl/issues/377.

@camilonova Since you have release permissions for this package as well, please basically do release manually again. The Jazzband website will soon have a better way to do PyPI releases (via https://github.com/jazzband/website/projects/1).

**Comment by camilonova** [comment]
@jezdez This one worked https://github.com/jazzband/django-axes/commit/94202905420a3daaa5a964398150dec97af65212

No need for me to do it manually.

**Comment by jezdez** [comment]
@camilonova I meant you need to do this manually in the future, I did the 2.3.0 release manually earlier.

**Comment by camilonova** [comment]
@jannisleidel Got it.
