### ISSUE TITLE
We are not getting the IP address in all cases

### ISSUE THREAD

**Issue by camilonova** [jazzband/django-axes#275]
Seems is better to use https://github.com/un33k/django-ipware instead of our current implementation.

If anyone wants to help with a PR for this change, please do so.

**Comment by TobitRE** [comment]
Maybe my error is du too this issue:
'NoneType' object has no attribute 'META'
/python3.6/site-packages/axes/utils.py in get_ip, line 118

I'm using python 3.6 and Django 2.0

**Comment by kakulukia** [comment]
Im also getting this error: 'NoneType' object has no attribute 'META'

**Comment by kdfler** [comment]
+1.
When I intendedly try to login with wrong credentials I always get the same error: 'NoneType' object has no attribute 'META'. When logging in with correct credentials no error occurs and I have the system logs everything correctly. 
I can reproduce the error anytime if you need it for the fix.

**Comment by kakulukia** [comment]
For my scenario i found cause of the issue which is the django rest framworkt jwt serializer using a deprecated version calling the authenticate method without a request object - hence the NoneType object. 
So i created an own version of the 'broken' serializer (which luckily already holds the request in its context) and the bug is gone. I dont know about the other error case, but in my case the 'bug' if you want to call it that way, ist to not expect the old authenticate call with just credetials from pre Django 1.11.

Id just throw an Exception when not getting a request, rather than trying to compensate the missing request object. But i guess that depends on the other error cases.

Anybody else using https://github.com/GetBlimp/django-rest-framework-jwt ?
I will try to create a pull request later since its just a small fix.

**Comment by kakulukia** [comment]
@camilonova shall i open a new issue for the: 'NoneType' object has no attribute 'META' error, because this is not fixed by your changes

**Comment by camilonova** [comment]
@kakulukia Please do. Thanks.
