### ISSUE TITLE
Potential security issues with `get_ip()` changes in v4

### ISSUE THREAD

**Issue by pope1ni** [jazzband/django-axes#286]
I'm a little concerned by the change to use `ipware.ip.get_ip()` in v4.

1. There is no documentation to suggest that `django-ipware` may need to be configured.
2. There is now no documentation on the potential attack vector if the proxy doesn't set `X-Forwarded-For` (or whatever the first header used in `IPWARE_META_PRECEDENCE_ORDER` is) explicitly, c.f. [`USE_X_FORWARDED_HOST`](https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-USE_X_FORWARDED_HOST)
3. ~~`django-ipware` says to use `get_ip()` if the server is **not** accessible on the Internet, see [here](https://github.com/un33k/django-ipware#how-to-use).~~ (Although looking at the code the distinction between `get_ip()` and `get_real_ip()`, the latter doesn't count private IP addresses as "real". What they really mean here is use `get_ip()` if there are also clients that may connect from an internal private network otherwise use `get_real_ip()`.)
4. Previously `django-axes` allowed configuring the maximum number of proxies in case of spoofed entries. This is no longer possible. `django-ipware` provides `get_trusted_ip()` but it isn't particularly useful in it's current form.

It would probably be wise to recommend setting `IPWARE_META_PRECEDENCE_ORDER` to `['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']` or at least indicate that this was the original behaviour. Checking all of these headers by default feels risky.

Forgive me, but this feels rushed and ill thought through. It was working fine for me and issue #275 and pull request #280 fail to even give any evidence of a problem. Every comment in #275 is regarding `AttributeError` when looking up `META` on `NoneType` - `django-ipware` is still using `request.META`. This feels like a push to remove code in favour of a dependency for minor gain.

**Comment by aleksihakli** [comment]
Hey, `django-ipware` indeed seems to be somewhat prone to proxy header injection and doesn't have the number of known proxies configurable. I previously contributed #225 which fixed IP address resolving by calculating the IP based on the number of proxies in the proxy chains, but using `django-ipware` scrubs this. Configuration for number of proxies is useful in e.g. AWS where there might be requests coming in directly to the web server reverse proxy whereas we would want request to flow through load balancers and into the web server; the configuration for the number fixes this and filters out unwanted requests with invalid headers.

It also seems that `django-ipware` also has a conflicted definition of how to use the proxy headers as seen here:

https://github.com/un33k/django-ipware/blob/master/ipware/defaults.py#L11

Whereas X-Forwarded-For should set the client IP as first address:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

There of course could be proxies that set the client IP as the last address but that would not be the de-facto standard way.

[I've opening an issue on the `django-ipware` for some further discussion on the matter](https://github.com/un33k/django-ipware/issues/33). Resolving IPs is smart to do in a specialized module, I think, and the development effort should be proxied there and documentation improved here :) Keeping things DRY will improve the life for everybody and `django-ipware` seems to have an active maintainer.

**Comment by un33k** [comment]
@aleksihakli & @pope1ni - Have a look at the ipware [how-to](https://stackoverflow.com/a/16203978/103734) on StackOverflow.  It was updated to better explain the package.

`django-ipware` evolved to what it is now.  Method naming could have been handled better.

Also: 

> Proxy Count

 You can pass-in a trusted proxy list with whatever length to match your `proxy count`  requirements.  This should cover the AWS load balancer requirement you have stated above.

> Whereas X-Forwarded-For should set the client IP as first address

The default behavior of `ipware` is `left-to-right` which is the de-facto standard. However, you can pass in the `right_most_proxy=True` to flip the direction if you have a custom proxy configuration.

Next major version will introduce a more streamlined way of handling all the above scenarios.

**Comment by un33k** [comment]
Proxy count is added to [ipware](https://github.com/un33k/django-ipware)

**Comment by aleksihakli** [comment]
Thanks a ton @un33k! I guess we'd just need to add the `AXES_NUM_PROXIES` flag with default `None` back to Axes and revise the usage of `get_ip` and we are good to go with this update.

**Comment by SunilMohanAdapa** [comment]
Current state of `django-axes` is that it is seriously broken and an adversary can completely bypass its IP limits.

`django-axes` uses the deprecated API from `django-ipware`.

If the Django application is deployed without a reverse proxy server, `django-axes` via `ipware` blindly trusts and uses the incoming headers. As a remedy, if `IPWARE_META_PRECEDENCE_ORDER` is set to an empty list, then `get_ip()` always returns `None`. This, at best, has the consequence of grouping all attempts into the same bucket.

If the Django application is deployed behind a reverse proxy server, then if the client sends a header (say an adversary intentionally does this) and proxy only appends to it (behavior for many proxy servers including Apache's `ProxyPass`, haproxy's `forwardfor` and nginx's `proxy_add_x_forwarded_for`), then the IP address from the client sent header is used. For example:

Django project is configured as:
```python
IPWARE_META_PRECEDENCE_ORDER=('HTTP_X_FORWARDED_FOR',),
```
Running under a WSGI server reverse proxied using Apache.
```sh
curl -H 'X-FORWARDED-FOR: 1.2.3.4' https://<server>/
```
In this case, `ipware.ip.get_ip()` returns `1.2.3.4` and not the IP address of the client. Hence, by continuously changing the header one can attempt any number of logins and bypass `django-axes`.

I believe the right course of action is to announce to the users that current version is insecure and quickly make a release with fixes.

**Comment by SunilMohanAdapa** [comment]
I think there are several aspects of `ipware.ip2` that could have been done better:

- Handling cases where Django project is not deployed behind a reverse proxy seems convoluted and undocumented. Caller has to set `IPWARE_META_PRECEDENCE_ORDER = ('REMOTE_ADDR',)` and set `proxy_count = None`.
- `proxy_count = None` is different from `proxy_count = 0`. This only causes confusion unless explained better.  `proxy_count = 0` seems to mean that there is one trusted server before the Django project.
- Why have some settings such as `IPWARE_META_PRECEDENCE_ORDER` be global settings and others such as `proxy_order`, `proxy_count` and `proxy_trusted_ips` be arguments when all of them are tightly related to how reverse proxies are configured? It is inconvenient to have apps send all the method parameters when they are likely to be same throughout the app.
- When there are client side proxies involved in the chain, `ipware.ip2` seems to want to return None due the following code:
```python
            if proxy_count > 0 and proxy_count != ip_count - 1:
                # we are expecting requests via `proxy_count` number of proxies
                continue
```
When client side proxies such as squid add 'X-Forwarded-For' and server side proxies append to it, then there is no way to properly configure the a Django project using ipware. The expected `proxy_count` will be different from `ip_count - 1`.

**Comment by SunilMohanAdapa** [comment]
> If the Django application is deployed without a reverse proxy server, django-axes via ipware blindly trusts and uses the incoming headers. As a remedy, if IPWARE_META_PRECEDENCE_ORDER is set to an empty list, then get_ip() always returns None. This, at best, has the consequence of grouping all attempts into the same bucket.

Looks like `IPWARE_META_PRECEDENCE_ORDER = ('REMOTE_ADDR')` is solution to this.

**Comment by camilonova** [comment]
@SunilMohanAdapa please make a pull request. Thanks.

**Comment by SunilMohanAdapa** [comment]
I have worked around the problem in my project by configuring the proxy to override the header sent from client.

**Comment by pope1ni** [comment]
@camilonova - please re-open this issue as the concerns raised have still not been fully addressed.

1. The default configuration of `django-ipware` is unsafe due to the full range of headers specified in `IPWARE_META_PRECEDENCE_ORDER`.
2. The lack of documentation in `django-axes` to warn that `django-ipware` and any proxy in front of `django-axes` need to be configured correctly.

What @SunilMohanAdapa has called a "workaround" is in fact what must be done to correctly and safely configure the proxy headers.

Putting this plainly, using a real example, `IPWARE_META_PRECEDENCE_ORDER` must not contain `HTTP_X_FORWARDED_FOR` if nginx does not do the following:

```nginx
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

Also note that this must be `proxy_set_header` and not `proxy_pass_header`. Without correct configuration, any client can set anything in the header bypassing any of the protection that `django-axes` claims to provide.

Obviously, `django-ipware` ought to set a safe default for `IPWARE_META_PRECEDENCE_ORDER`, using values such as `REMOTE_ADDR` which are usually automatically explicitly set by the server, but that ship has sailed. Ideally it should force you to specify the one header that you expect, and have none by default raising [`ImproperlyConfigured`](https://docs.djangoproject.com/en/stable/ref/exceptions/#improperlyconfigured). (Ping @un33k)

As mentioned when I opened this issue, please compare to [`USE_X_FORWARDED_HOST`](https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-USE_X_FORWARDED_HOST) in Django.

This change to use `django-ipware` was made in 9ecbf4cf6 by you @camilonova and, as mentioned in the last paragraph when I opened this issue, didn't actually address the issues referenced. It also removed any references to the security-related concerns in the documentation, vague as they were, when then the documentation for all of the options was ripped out.

**Comment by camilonova** [comment]
@pope1ni Nick thank you for explaining. I understand what you mean, what do you propose to fix it?

I did change the library to use django-ipware because I think is better to use them than to code and maintain the logic in this library, which has a different purpose.

But I get your point, if you think there is a better (safer) alternative please go ahead and improve it.

Maybe this security issue should be handled by django-ipware and not by django-axes. I do support what is best for the library, even if is replacing django-ipware.

**Comment by aleksihakli** [comment]
I think the correct fix is to improve documentation to support the configuration of `django-ipware` so that it is compatible the idea of how `django-axes` should function.

@pope1ni would you like to contribute the necessary documentation?

**Comment by SunilMohanAdapa** [comment]
I propose the fix as follows:

* ipware to introduce ipware.ip3.get_client_ip() to fix current issues.
* ipware to not take any parameters other than request. The rest should be configuration. That will make the library more useful. django-axes and other users need not introduce their own configuration parameters just to pass to ipware.
* ipware to default to assuming that the service is not running behind a proxy server as @pope1ni suggested. Assuming direct service by default is secure in all cases. Assuming behind proxy by default in insecure in some cases. This is similar to Django itself.
* ipware to not have precedence order at all. Instead it should only allow specifying a single header to extract client address from. Allowing multiple headers opens users to security problems. It is hard to imagine a use case for accepting two headers securely. Have two proxies that send two different headers? You need to configure each one of them to reset the other header anyway, so why not configure them to send the same header? Falling back to REMOTE_ADDR when configured header value is unexpected may be okay.
* ipware to not assume that ip address count in the value of header will be same as number of proxies. This assumption easily fails when clients send their own header and proxies append to the headers (default for most proxies).
* ipware to thoroughly document all the settings and their security implications.
* (optionally) ipware to implement more thorough handling of trusted proxies. This include consideration for checking REMOTE_ADDR itself in proxy list and performing normalized ipv6 address matching.
* (optionally) ipware to parse the 'Forward' header differently according to [RFC 7239](https://tools.ietf.org/html/rfc7239).
* django-axes to make no changes expect for asking users to look at ipware documentation for configuration in case the project is deployed before proxy servers. Default will be to assume that service is not running behind proxy.

**Comment by aleksihakli** [comment]
That all sounds good and well but you will have to open the issues and pull requests into the [django-ipware](https://github.com/un33k/django-ipware) project. I think that it is unreasonable to ask for the author to implement changes to only benefit `django-axes`, so contributing that new `django-ipware` utility would be the prompt thing to do, if you want it.

`django-axes` and `django-ipware` do not share the developers or code base, and `django-ipware` seems pretty well designed to me, in all honesty. Parsing end user IPs is a best effort task and can not be done with 100% reliability, and hence the end user IPs shouldn't be relied on too heavily in terms of authentication. They can be used to augment the authentication flow to distinguish forged authentication requests coming from a single computer and ban that IP, but they have little use outside of that.

The solution in `django-axes` at this time is to improve the documentation to include instructions on configuring `django-ipware` in a sane fashion. This can, in my opinion, be as simple as directing the user refer to the `django-ipware` in the [configuration documentation](https://django-axes.readthedocs.io/en/latest/configuration.html).

**Comment by SunilMohanAdapa** [comment]
On Thursday 22 March 2018 11:47 PM, Aleksi Häkli wrote:
> That all sounds good and well but you will have to open the issues and
> pull requests into the django-ipware
> <https://github.com/un33k/django-ipware> project. I think that it is
> unreasonable to ask for the author to implement changes to only benefit
> |django-axes|, so contributing that new |django-ipware| utility would be
> the prompt thing to do, if you want it.
> 
> |django-axes| and |django-ipware| do not share the developers or code
> base,

I understand. My special thanks to @un33k for proactively looking at
this issue and coming up with fixes in django-ipware.

> and |django-ipware| seems pretty well designed to me, in all
> honesty.

I hope the large number of issues @pope1ni and I pointed out here
convince you otherwise.

> Parsing end user IPs is a best effort task and can not be done
> with 100% reliability,

Determining remote address in a IP connection need not be guesswork.
When trusted proxies are properly configured, it should be possible to
accurately determine the remote address.

The current implementation (django-axes + django-ipware) makes this
guesswork by making several false assumptions. It makes properly
configuring the network harder.

> and hence the end user IPs shouldn't be relied on
> too heavily in terms of authentication. They can be used to augment the
> authentication flow to distinguish forged authentication requests coming
> from a single computer and ban that IP, but they have little use outside
> of that.

Note that if None (or wrong IP) is returned for get_client_ip() due to
guesswork, it becomes possible to do denial-of-service attacks on
resources protected by django-axes. So, please don't take the issue lightly.

> Please refer to the example answer @un33k has made above. There are a
> number of ways to circumvent proxy count checking if any aspect of
> network security has been overlooked, which is the case in many
> projects.

This only happens because ipware makes the fatal mistake of not checking
REMOTE_ADDR in list of trusted proxies. REMOTE_ADDR is accurate and can
be trusted unlike HTTP headers. This is the starting point of the trust
chain. My proposed fix addresses the problems.

Also, the assumption here is that an adversary is able to make requests
to the service from within a private network after breaching network.
This is a far fetched case considering how we have problems with some
basic things.

[...]

I will try to make patch for both projects if I get some time to spare.
But looking at my backlog, I encourage others to do that.

Changes in axes or ipware, from me or axes or ipware devs, I urge you
all fix all the problems fundamentally and not close this issue off. It
would be a disservice to the users of both projects.

Thank you,

-- 
Sunil

**Comment by EvaSDK** [comment]
Thanks a lot to @pope1ni and @SunilMohanAdapa for explaining the problem clearly. I reached the point in my roadmap where I needed to look into upgrading django-axes for the project I maintain and I had to read the code to figure out how to properly upgrade from v2 and figured out all configuration wrt proxies was actually removed making django-axes a useless brick in my company's codebase. I will look into getting some time to fix django-ipware but it is more likely that we will have to stick with the older release.

**Comment by aleksihakli** [comment]
@EvaSDK and all other conversation participants, the issue you are discussing is related to your proxy configuration and `django-ipware` configuration, not `axes` being broken. 

You need to, obviously, configure your reverse proxy to correctly pass / add / set headers and [configure `django-ipware` to check those headers strictly by setting the `IPWARE_META_PRECEDENCE_ORDER` key](https://github.com/un33k/django-ipware/blob/master/README.md#advanced-users) if you wish to implement functional IP checking for your project. There are configuration options for that. 

Any real project setup will require you to configure the reverse proxies you are using. I hope you are not blindly running your Django deployment without a correctly and thoughtfully configured reverse, at least.

The main thing to do regarding `axes` is to improve the documentation to explain these things to the end user, but please notice that *security does not come to your project by installing an arbitrary package from the Internet, even if that package claims to check this or that stuff and make your project more secure*. 

You need to actually understand what the packages you use do, why they do what they do, and whether or not you should use them. 

You also need to understand that discussing `django-ipware` package issues in `django-axes` issue tracker is not productive; if you wish to change how `django-ipware` works open an issue or PR there, or if you wish to change the `axes` functionality, open a PR here.

**Comment by EvaSDK** [comment]
Don't worry, I think we all understand this. I guess the problem is that it is a regression from django-axes from our point of view.

For example, no amount of configuration from django-axes or django-ipware can get `ip2.get_client_ip` as used in https://github.com/jazzband/django-axes/blob/3a2fb808840666a59ad863325249aae4e74b9aea/axes/attempts.py#L18 to be trusted.

What's suggested by @SunilMohanAdapa  in https://github.com/jazzband/django-axes/issues/286#issuecomment-375334632 needs to be ported to django-ipware bug tracker and fixed.

**Comment by aleksihakli** [comment]
How is it not secure or trusted? If you configure the following:

    IPWARE_META_PRECEDENCE_ORDER = ('REMOTE_ADDR', )

You are good to go if you are not running behind a reverse proxy. `ipware` should not check for additional headers, and you will get the value for `REMOTE_ADDR` as your end user IP.

If you do have a reverse proxy, for example `nginx`, that *sets* the client header instead of appending to a header value to a chain of headers provided by the client making the request, you are also good to go:

    # nginx configuration for location with http_realip_module enabled
    proxy_set_header X-Real-IP $remote_addr;

    # Django project configuration for ipware
    IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_REAL_IP', 'REMOTE_ADDR', )

The cases where `django-ipware` becomes unsecure is

1. when you are using the default `ipware` `IPWARE_META_PRECEDENCE_ORDER` headers (or `request.META` values to be exact) to check the client IP and you allow a client to set and your proxy to forward those headers arbitrarily (which is how many proxy servers work out-of-the-box), or
2. you check against an appended header value such as `X-Forwarded-For` or `request.META['HTTP_X_FORWARDED_FOR']` in Django terms, for which we can not currently configure the `proxy_count` as used by `ipware` at this moment. We can add a configuration flag for this to allow for accounting of proxy count as well.

https://github.com/un33k/django-ipware/blob/a71d956c1c3c21c80e742823687f39e970e1147c/ipware/ip2.py#L5

The things that can happen to your project because of this are

1. someone is able to make multiple authentication requests from a single IP by spoofing headers, bypassing `axes` lock out mechanisms, which any serious attacker apart from a script kiddy with a single computer will indeed do if they are really interested in breaching your site by e.g. using a fleet of low cost spot pricing cloud servers that have changing IPs, or
2. you lock out users by accident because you use e.g. the `REMOTE_ADDR` attribute behind a proxy which gets set to `127.0.0.1` and you end up seeing multiple authentication requests coming from the same address, locking that address, and all your users that seem to use the same address, out.

The case that is really potentially insecure here is case 1, where you allow your clients to effectively inject semantical headers that you use for secure checking into your service, and do not check their semantics or counts. Even after bypassing the lock out mechanisms your attacker still has to brute-force their way in, usually requiring and unrealistic amount of attempts over a slow HTTP connection over TCP/IP socket as an attack vector and a brute-force attack against (most probably) PBKDF2 hashing, which is rather slow as default. Then your attacker has to actually gain access to a meaningful account to exploit your service, meaning that you have to have a service that requires heightened security running with non-MFA staff users. After those steps, yes, an attacker can gain access to your accounts, and if you use single-factor authentication as in just a password to actually log in as a staff user in a heightened security online service, I'd say you are actually fucked by design.

Or is there something I'm missing here? Is there an easier and simpler attack vector that is open, if you have configured your proxy, `ipware`, and `axes` correctly?

**Comment by vdboor** [comment]
I'm all for making this the default:

```
IPWARE_META_PRECEDENCE_ORDER = ('REMOTE_ADDR', )
```

that would at least provide secure defaults. (I've suggested this back in 2015: https://github.com/un33k/django-ipware/issues/8)

A good alternative solution is https://pypi.python.org/pypi/WsgiUnproxy which acts as wsgi middleware. It corrects `request.META['REMOTE_ADDR']` to point to the proper address only when the request came from a trusted list of IP addresses. This not only fixes django-axes, but also all other third party package like contact forms, rate limiting and raven/sentry to read the same IP address. It makes django-ipware pretty much obsolete imho.

For AWS, there is https://github.com/LabD/wsgi-aws-unproxy

Example:

```
from django.core.wsgi import get_wsgi_application
from netaddr import IPNetwork
from wsgiunproxy import unproxy

application = get_wsgi_application()
application = unproxy(trusted_proxies=IPNetwork('10.0.0.0/8'))(application)
```

**Comment by un33k** [comment]
FYI,

ipware [2.0.2](https://github.com/un33k/django-ipware/tree/2.0.2#advanced-users) allows for this ...

```python
get_client_ip(request, request_header_order=['X_FORWARDED_FOR', 'HTTP_X_FORWARDED_FOR'])
```

**Comment by aleksihakli** [comment]
@un33k thanks! We'll add an `axes` configuration with strict defaults for sending the proxy count and request header precendence order to `ipware`. That should solve this problem :+1:

**Comment by EvaSDK** [comment]
@aleksihakli, after considering your comment (https://github.com/jazzband/django-axes/issues/286#issuecomment-380370147) and checking our stack, I think I now agree with you than it is sensible to only consider {{REMOTE_ADDR}} as the source of information for client's IP address, be it behind proxies or not, and no changes to django-axes are required.
Using {{REMOTE_ADDR}} as the single source of truth makes everyone's code easier and hopefully avoids fallbacks to broken headers by default.
For what concerns the project I work on, raven and django-axes now behave properly and I just need to patch django-analytical to use django-ipware as well or at least unset X-Forwarded-For so it does not report incorrect data.
