### ISSUE TITLE
Should axes use the request.POST data or authenticate's **credentials?

### ISSUE THREAD

**Issue by markddavidoff** [jazzband/django-axes#358]
In my use case, I process the POST to get the user we pass to `authenticate` from different endpoints in different ways. This is a hassle to reproduce in `AXES_USERNAME_CALLABLE`. I think instead, we should pull username and password from the args passed to authenticate instead of from the `request.POST`. Furthermore, request being present depends on it being correctly passed by 3rd party backends even though Django mentions it is an optional parm in the docs.

Input? @camilonova @aleksihakli @aclark4life @codekoala

**Comment by markddavidoff** [comment]
It's also weird that we do `request.POST.get(settings.AXES_USERNAME_FORM_FIELD, None)` in some places and `credentials[settings.AXES_USERNAME_FORM_FIELD]` in others.

**Comment by markddavidoff** [comment]
I am willing to open a PR with changes to use credentials instead of request.POST for username fields but this would be a big-ish change so i want to know if people would be on board with it.

**Comment by camilonova** [comment]
Using credentials sounds good to me.

**Comment by mastacheata** [comment]
I'd like to suggest considering this as a bug.
Two reasons for this:
#1 Inconsistent behavior between storing the access attempt and looking it up.
#2 What if you send the username in a different way than as a POST form field?

Especially #2 makes this a huge PITA for me. We're submitting login credentials via JSON inside the POST body. Now Axes has no problem with storing the right stuff to the database, but if we use Username or Username+UA as the main identifier instead of the IP address, this will cause Axes to create new entries in the axes_accessattempts table instead of updating an existing record and increasing the failed login count. It tries to perform a lookup based on None as the username and that obviously fails.

**Comment by aleksihakli** [comment]
@mastacheata good consideration, added the bug label.

**Comment by aleksihakli** [comment]
Fixed by #377 and #380.
