### ISSUE TITLE
GET requests always skipping lockout check

### ISSUE THREAD

**Issue by libcthorne** [jazzband/django-axes#398]
Hi. I'm using `django-axes` in a HTTP API with Basic Auth. The API accepts `GET` and `POST` requests, and all requests have the Basic Auth header to extract credentials from. To integrate with `django-axes`, I pass the credentials manually into `django.contrib.auth.authenticate` (using the `username` and `password` parameters) and have `AxesModelBackend` included in `AUTHENTICATION_BACKENDS`.

This has seemingly worked fine up until recently, when I upgraded `django-axes` from 2.3.3 to 4.4.0. After upgrading, I've noticed that GET requests are no longer subject to lockout, and found this change to be the reason: https://github.com/jazzband/django-axes/pull/262/files#diff-98c00a3d39f41b919aeb159f2b5dd247R436

I understand why the change was made (https://github.com/jazzband/django-axes/issues/261) but was wondering if it could be extended slightly to still support checking `GET` requests under certain conditions. I think, with the latest version of `django-axes` (https://github.com/jazzband/django-axes/blob/4.5.4/axes/attempts.py#L183), something like `(request.method == 'GET' and credentials is None)` would work for me and still address https://github.com/jazzband/django-axes/issues/261.

I'm happy to open a PR if this is considered a valid issue but wanted to ask for advice first.

Thanks.

**Comment by aleksihakli** [comment]
@libcthorne I think that GET requests are also valid if basic authentication is used, and they should be monitored as well.

The [`is_already_locked` function](https://github.com/jazzband/django-axes/blob/60f2a8ed71698225fa93ca4047d61cfbdad0eac2/axes/attempts.py#L183) should be reviewed and documented better. 

I agree in that if there is a GET check, it should be separate from that complex and composite check. I think the correct way to separate the GETs would be to add a flag that enables separate GET checking and document the whole function better. 

Please feel free to open a PR for the suggested solution. We are just working on Axes version 5, so I think now is a prime time to improve things.

**Comment by aleksihakli** [comment]
@libcthorne this is now fixed in master with https://github.com/jazzband/django-axes/commit/cd56631865ec483fb3b791d35c4cced4f8f8c4e8 and will be released in Axes version 5.

**Comment by libcthorne** [comment]
Thanks @aleksihakli! I had a quick read of the fix and it looks like it will cover our use-case.
Am I right in understanding Axes version 5 is Python 3 only? The team I'm working with are planning to upgrade at some point in the near future, but I might not be able to test immediately.

**Comment by aleksihakli** [comment]
@libcthorne yeah, Axes 5 will be Python 3 only.

@camilonova suggested we drop the Python 2 support in the version 5 release and clean up the code base from the compatibility patches, and after some thought I agree that the drop is sensible at this stage.

I am sorry if it causes inconvenience but Python 2.7 EOL is coming pretty soon, in 2020, and I think it is better to release the version 5 as Python 3 only. We would otherwise have to release a version 6 for dropping the old language version support as we are using [semantic versioning](https://semver.org/), and I hope that Axes 5 will be a long lived version. Python 3.4 is also deprecating very soon, before the summer 2019.

With Python 3.5 we get nice features like type annotations and access to the new Python 3 APIs and can run all tools in Python 3 mode.

You can also make a fork and change the relevant few lines for testing or e.g. apply a patch in your testing environment that changes this block of code:

- https://github.com/jazzband/django-axes/blob/820ecca23601f605919b01803fcb142431febf72/axes/attempts.py#L204-205
- https://github.com/jazzband/django-axes/blob/8c73eed7260d91bbb47d5d07842f1c0258fb14a0/axes/attempts.py#L182-186
