### ISSUE TITLE
Add cached backend handler

### ISSUE THREAD

**Issue by jorlugaqui** [jazzband/django-axes#401]
As per the conversation happening in https://github.com/kencochrane/django-defender/issues/121#issuecomment-461617352, this issue aims for getting a pluggable cached backend for django-axes. 

If you don't mind, I could give it a try.

**Comment by aleksihakli** [comment]
@jorlugaqui sounds awesome, if you have the time to spare I would greatly appreciate the help! Just go ahead and open a PR and let's see how things turn out.

I am also playing around the current middleware - backend - handler structure and thinking on how to clean it up so that the locking checks would be simpler. Big part of this work is in the refactoring of the current implementation.

I think that working on the purely cached backend solution on a parallel track would only be beneficial for both tracks.

It could also help us possibly improve the current API structure before freezing and releasing it in Axes version 5. We can't really change things around after baking that release, but have plenty of flexibility at this time, so go ahead and propose the changes you would like to see if you have any ideas.

**Comment by aleksihakli** [comment]
@jorlugaqui @camilonova I think that the handler layer could benefit from moving the Axes internal method `axes.attempts.is_already_locked` into the handler class.

The `is_already_locked` function being in the handler layer would allow us to just change the handler implementation for checking the lockout status, and using the default Axes authentication backend and middleware for the lockouts.

The handler could then execute the lockout checks on the correct layer (database or cache or e.g. static ruleset).

The `is_already_locked` method is currently called from the decorators, the authentication backend and the signal handlers in the current implementation, once during the authentication backend which checks if the user is allowed to log in and another time in the signal handler which checks if the user should be locked out:

- https://github.com/jazzband/django-axes/blob/ad2ed23ced5590d8a936f3194a895dd69d3e5707/axes/decorators.py#L9
- https://github.com/jazzband/django-axes/blob/ad2ed23ced5590d8a936f3194a895dd69d3e5707/axes/decorators.py#L20
- https://github.com/jazzband/django-axes/blob/ad2ed23ced5590d8a936f3194a895dd69d3e5707/axes/backends.py#L39
- https://github.com/jazzband/django-axes/blob/ad2ed23ced5590d8a936f3194a895dd69d3e5707/axes/handlers.py#L117

The implementation would be fairly easy to move, I think:

- https://github.com/jazzband/django-axes/blob/ad2ed23ced5590d8a936f3194a895dd69d3e5707/axes/attempts.py#L188

Just hoist that function implementation into the handler class.

I think the overall API design for Axes version 5 should focus on the handler layer and we should figure out what the final, extensible API should look like for that particular class.

Handler is the place we would most probably like to be implementing any pluggable authentication checks and logging, and having a good API on that layer would allow users to easily extend the default Axes implementations by simply inheriting from a suitable Axes handler and overriding the method implementations with their own implementations or adding their own hooks before or after the stock methods if they want to do so.

At the moment the handler only implements the signal receiver APIs, but those could easily be augmented, improved and documented at this stage.

**Comment by aleksihakli** [comment]
Pluggable handlers implemented in #402, if everything is OK in the PR it should be fairly easy to actually implement a cached handler backend on top of that, just specialize the `axes.handlers.base.AxesBaseHandler` and set `settings.AXES_HANDLER` to the path of the new cached handler backend, for example `settings.AXES_HANDLER = 'axes.handlers.cache.AxesCacheHandler'`.

**Comment by aleksihakli** [comment]
Pluggable handlers upstreamed into master, please implement any changes on top of the current changes in case you are working on the cached handlers.

**Comment by aleksihakli** [comment]
First version of the cached handler is upstreamed now @jorlugaqui. I'll leave this issue open for a while if you'd like to discuss refining the design and next steps. 

If you have any ideas on how to improve the design or implementations please do tell.

**Comment by aleksihakli** [comment]
I think some of the concrete ideas on the handler would be to:

- Improve the middleware (or the handler) implementation so that it would calculate the necessary request attributes once instead of fetching them in each and every implementation. This requires implementing tests and making the middleware class more reusable since people would need to use it in their own specialized implementations as well. Username needs to be calculated on spot, but some others that come to mind are:
    - `request.axes_attempt_time` could be a `datetime.datetime` stamp
    - `request.axes_ip_address` could be a validated `ipaddress.IPV4Address`
    - `request.axes_user_agent` could be a string indicating the user agent
    - `request.axes_path_info` could be a string indicating the path
    - `request.axes_http_accept` could be a string indicating the accept value
- Improve the internal handler implementations of the database and cache handler and remove duplicate code.
- Improve the handler base class and make it an abstract base class or `abc.ABC` with correctly marked `abc.abstractmethod`s. This requires refactoring the test suite for the handlers.
- Improve the test suite in `axes.tests.test_login`; at the moment it's quite crufty and hard to read.
- Improve the documentation for extending Axes with custom implementations.
- Add integration tests for common Django apps that are used alongside Axes. Some that come to mind are:
    - Django REST Framework, 
    - Django Allauth, and
    - Python Social Auth.

**Comment by jorlugaqui** [comment]
@aleksihakli Agree. I would add (maybe is already covered in the second item) to make functions more singulars, meaning make them do (as much as possible) one thing.

**Comment by aleksihakli** [comment]
@jorlugaqui yeah I think adhering more to single responsibility principle would improve the codebase, at the moment some functions do two or three things.

I've split the issues discussed here into separate issues and will close this mega ticket issue.

The cache handler is now implemented and the ideas from here have been documented, and I think it's better to continue discussion in #396 regarding combining Defender and Axes functionality.
