### ISSUE TITLE
GDPR discussion

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#438]
Hi guys,

just talked with my colleage about the issue that with the new EU GDPR law you are basically not allowed to save IP addresses anywhere.

We came up with the idea to make a settings variable. If this is enabled, IP addresses get saved as a hash.

Any thoughts about that solution?

Best from Europe
Ronny

**Comment by aleksihakli** [comment]
Hi Ron,

and thanks for opening the data protection discussion! I think that user anonymity and minimal storage of user information is an important aspect of good engineering whenever it is possible.

Firstly, as a disclaimer, I am not an expert on the GDPR and European privacy legislation, so please do double check the views and ideas presented here. These are not facts, but only my personal and possibly faulty viewpoints on the matter, presented purely for the purpose of discussion.

As a philosophical viewpoint: As far as I have understood, the saving of IP addresses themselves is not technically prohibited by GDPR. Saving them without a lawful purpose is. The users should be informed about any and all information that is gathered about them, and be presented an option to review and request removal of that information, if at all possible. Some information must always be stored about users that register and login into a site, since it is necessary to identify users. It is not possible to identify users or people uniquely without some information about them. The responsibility of making a privacy policy that clearly states the principles of data processing, storage, and usage falls to the responsibility GDPR registry holder and data processor, and all websites should have their policies easily available to users. Systems should at least inform users that if they register or login into a system, their information such as username, password, IP address and timestamp of the login might be processed and stored.

As a technical viewpoint: The IP address is a fairly short string of information. The IPv4 address contains 32 bits, which is just 4 bytes. That is the equivalent of 4 ASCII characters. Think of a 4 character password. That isn't very strong, even with a very computationally expensive hashing function. Hashing a 32-bit key space with a deterministic one-way hashing function would result in a value space that is easily computed on the fly for all possible key-value pairs on a modern microcomputer. Hence, I don't think that hashing itself would solve the need for anonymity in this specific case, if one can simply crack all the addresses in the database on the fly.

One valid option would be to increase the size of the request attribute hashing. If we used the whole unique combination of the request attributes such as username, user agent, and IP address, it would make the source address space larger and would make calculating target space values fairly difficult. 

On the other hand, if the administrator blocks the attempts by user IP address only, that reduces the request attributes to only the IP, so we're back to square one on the hashing problem.

**Comment by aleksihakli** [comment]
And by the way, you can implement a custom handler that does not store the attempts at all. Please take a look at the [`AxesHandler`](https://github.com/jazzband/django-axes/blob/master/axes/handlers/base.py) and the [`AxesDatabaseHandler`](https://github.com/jazzband/django-axes/blob/master/axes/handlers/database.py) for inspiration. After implementing a custom handler, you can just [swap out the default handler](https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-handlers) with the `AXES_HANDLER` configuration flag. This would solve the IP address storage problem in your case. You can use your own custom models with your own handler and implement and store the hash values there as you see fit.

**Comment by GitRon** [comment]
@aleksihakli Great idea overriding the handler! Maybe it would be cool to have one out-of-the-box in axes so people can behave GDPR-correct by setting up axes in their project?

**Comment by aleksihakli** [comment]
Yeah, that is a valid idea. An anonymous stock handler wouldn't be overly complicated. One thing to note is that the IPs should be redacted from all log messages as well.

Please do feel free to open any and all PRs for features you would like to see in Axes. The project is pretty easy to setup, develop, and test with the tox test runner.

**Comment by GitRon** [comment]
@aleksihakli Thanks for the hint with tox!

Second: I looked at the source code and played around a little with hashing ip addresses. Do you think we could just hash the ip address inside the `AxesRequest` and then let the database handler to it's work? Maybe create a new class based on `AxesDatabaseHandler` and manipulate every request object which goes at some point inside the class?

**Comment by aleksihakli** [comment]
I believe the correct place for storing the information would be the handler entirely, where you could anonymize logging as well. 

While going about it, it could be smart to anonymize the username as well, and just store a hash of the attempt, similarly as in the cache handler? 

Then you could just store the hash of e.g. (username, IP, user agent) as configured, with the necessary timestamps, and there would be

- no log trail, and
- no database trail of specific users.

The difficult thing would be unlocking failed attempts, of course.

As said before, you probably need to use more keys than just the IP to actually anonymize the attempts, as iterating over IP or username keyspaces would be fairly fast since they are so small.

**Comment by GitRon** [comment]
Hm, good point. Do you have a good idea how I'd be able to make a more secure hash?

And do you know if the current implementation would accept a hash in the IP field? I'd like to avoid adding new nullable fields...

**Comment by aleksihakli** [comment]
Adding a separate model would probably be smartest since other attributes might have to be redacted as well. 

The IP field needs a valid IP address. 

Hash "strength" can be improved with more hashing parameters. One option would be to use a secret salt that is loaded through e.g. settings, which can be prepended to the hashes. Another option would be to combine multiple attributes like username and user agent to the hash as discussed before :) Check the cache handler for inspiration on that.

**Comment by aleksihakli** [comment]
Closing as this issue has not received more discussion in half a year :)

**Comment by GitRon** [comment]
Hi @aleksihakli unfortunately I had a big project the last couple of months. Still have the topic on my todo list though... Will post update if I manage to tackle the topic!

**Comment by aleksihakli** [comment]
Great to hear! We can naturally reopen the discussion if we get new viewpoints, solution models, or updates. This closing of the issue was purely for housekeeping purposes :)

**Comment by GitRon** [comment]
Hi @aleksihakli 

finally we found a solution thanks to v6. If we set `AXES_CLIENT_IP_CALLABLE` to a function returning `None` and `AXES_ONLY_USER_FAILURES=True`, we don't save the IP address but still do have lockout functionality.

I think it would benefit the project if we would document this in a way that other people caring about privacy find this quickly.

```
AXES_ONLY_USER_FAILURES=True
AXES_CLIENT_IP_CALLABLE = lambda x: None # noqa: E731
```

What do you think? Would you be open for a PR?

Best  
Ronny

**Comment by aleksihakli** [comment]
We're always open for PRs, please do feel free to open one if you think there's synergies or it could make someone else's life a bit easier :)
