### ISSUE TITLE
Bug with counting access attempts and locking out user

### ISSUE THREAD

**Issue by sbaum** [jazzband/django-axes#442]
Hi, I have a major problem with the current behaviour of django-axes. It invalidates the protection against brute-force login attacks.

Django is running in autocommit mode (which is default). These are the relevant axes settings:

```
AXES_ONLY_USER_FAILURES=True
AXES_FAILURE_LIMIT=5
AXES_DISABLE_SUCCESS_ACCESS_LOG=True
```

In `handlers/database.py` the access attempt counter gets updated with the following statement:

```
            attempts.update(
                get_data=Concat('get_data', Value(separator + get_data)),
                post_data=Concat('post_data', Value(separator + post_data)),
                http_accept=request.axes_http_accept,
                path_info=request.axes_path_info,
                failures_since_start=failures_since_start,
                attempt_time=request.axes_attempt_time,
            )
```
So when I try to login with a wrong password 5 times in a row, `failures_since_start` has a value of 5 and is send to the database with that update command.
As `failures_since_start` then has reached the AXES_FAILURE_LIMIT value, the following code in `handlers/database.py` purposely raises an AxesSignalPermissionDenied exception:

```
        if failures_since_start >= settings.AXES_FAILURE_LIMIT:
            log.warning('AXES: Locking out %s after repeated login failures.', client_str)

            user_locked_out.send(
                'axes',
                request=request,
                username=username,
                ip_address=request.axes_ip_address,
            )

            raise AxesSignalPermissionDenied('Locked out due to repeated login failures.')
```

My understanding is, that this exception leads the current database transaction (we are in autcommit mode!) to be rolled back. (My database log shows the ROLLBACK command sent to the database.) But that ROLLBACK resets the stored `failures_since_start` to the previous value of 4.
In effect an attacker can keep trying different passwords without any limit until he finds the right one, because `failures_since_start` never gets stored in the database as soon as it reaches the value of AXES_FAILURE_LIMIT.

First question: Is my understanding of the problem correct?
Second question: If it is, how can this problem be resolved?

Thanks!

**Comment by aleksihakli** [comment]
Hi, and thanks for reporting this! This seems like a bug or flawed design in the handler API and requires further investigation, but it seems the transaction rollback is a very possible explanation for the faulty behavior you are experiencing. If you are correct, then we'll need to iterate on the way that the locking out works in the API layers.

At the moment, the authentication backend first stops the authentication flow with the `AxesBackendPermissionDenied` exception, and then the signal handler kicks in and raises the `AxesSignalPermissionDenied` exception. We might need to change the signal handler exception into something different than an exception in order for the lockout to work, since the current approach might cause the transaction rollback.

Using something else than an exception in the handlers would have the added bonus of not preventing any other signal handlers from running, and could in fact be better in architectural sense as well. The downside is that we might have to figure out a new way for generating the lockout response in the middleware or some alternative layer.

Would you happen have a better approach than the current exception handler in the middleware?

**Comment by sbaum** [comment]
Unfortunately I don't have a better approach, as I'm no expert on Django internals. I was hoping you'd have a brilliant idea. ;-)

**Comment by aleksihakli** [comment]
Well, one option is to just leave out the `AxesSignalPermissionDenied` exception, so that the signal handler does not raise at all, which would probably solve the issue. We would need to somehow handle returning an error view in that case. It seems like reading through the Django exception handling logic and database transaction rollbacks is the only smart way to go about solving this.

**Comment by aleksihakli** [comment]
@sbaum would you mind checking out #443? I implemented an alternative way for marking the requests for lockout. All the tests work and this should ideally fix the problem in release 5.0.5.

**Comment by aleksihakli** [comment]
@sbaum would you mind checking if version 5.0.5 fixes the issue for you? It is released on PyPI.

**Comment by sbaum** [comment]
I will check it and give feedback as soon as possible, but I'm currently on a business trip til next thursday (without access to my development system).

**Comment by sbaum** [comment]
@aleksihakli Problem is fixed! Thank you!

**Comment by aleksihakli** [comment]
Great, thanks for your help :)
