### ISSUE TITLE
Should axes_reset with DummyBackend fail silently?

### ISSUE THREAD

**Issue by aidanlister** [jazzband/django-axes#546]
Should axes_reset with DummyBackend fail silently? I think so, as DummyBackend is going to be used for testing ... I don't care if it's not implemented - the implementation should be a null method.

**Comment by aleksihakli** [comment]
Hey @aidanlister! You have a good viewpoint. I assume you are talking of the `AxesDummyHandler`.

The current behaviour of ”loud failure” with an exception was opted for because django-axes is a security oriented project and some people think that implicit failure is a bad practice in a security context.

You can implement a custom handler and use it in your own project. The API for handlers can be considered stable and you can just specialize the `AxesBaseHandler` per your liking.

**Comment by aidanlister** [comment]
Could you include a AxesTestHandler then, for a sane configuration for testing?

**Comment by aleksihakli** [comment]
@aidanlister sure, we could include that. Would you like to open a PR for the handler?

**Comment by aidanlister** [comment]
Done

**Comment by aleksihakli** [comment]
Released in 5.2.0.
