### ISSUE TITLE
Lockout doesn't kick in if spamming requests quickly

### ISSUE THREAD

**Issue by dh7892** [jazzband/django-axes#592]
Hi, 

We are using your fine package with the rest framework and have found an apparent problem.

If I try to hit our auth token endpoint with invalid credentials, it correctly blocks me after the 5 attempts. But if we spam that endpoint really hard (i.e we kick off 100 requests via async), it lets ~15-20 attempts go through before locking it down. 

By printing out a few messages from the Axes signal and decorator code, it appears that the requests are being processed before the failed attempts are getting saved in the db. This may well be more to do with how DRF handles requests than the Axes code per se, but it does cause us a problem. 

I have reproduced this issue even on a local Dajngo server with the `--nothreading`  so I don't think it's related to multi-threading race conditions. But I don't really know too much about how simultaneous requests are processed in DRF. It certainly seems like it's processing some of the request before it's finished the last request. Maybe it's the signals that get processed later? 

I think our solution, for now, is going to be to throttle that endpoint (which is obviously a good thing to do anyway), but I wanted to raise the issue in case I'm doing something wrong or in case it highlights anything you can improve about Axes.

**Comment by aleksihakli** [comment]
This has to do with how Django itself functions and is not caused by DRF or Axes, although they are affected by it as well.

https://docs.djangoproject.com/en/3.0/topics/db/transactions/

tl: dr; if you want to prevent distributed attacks you have to enable atomic transactions for databases queries, which will slow your code down, and possibly configure your web server so that it handles the HTTP requests sequentially only. Rate limiting or building mutexes into the authentication flow is another option.

I'm leaving this open as this is a good point to discuss and ideas are welcome on how to improve the Axes design.

**Comment by dh7892** [comment]
Thank for the detailed response. That makes perfect sense and lines up with what I observed.
