### ISSUE TITLE
Increment the number of failed login attempts atomically in AxesCacheHandler

### ISSUE THREAD

**Issue by okapies** [jazzband/django-axes#784]
`AxesCacheHandler` has a chance to increment `failures_since_start` badly where multiple worker processes receive many concurrent login attempts during the short period (e.g., DDoS). It requires to use of the atomic counter functionality inherent in the caching mechanism like [`INCR` in Redis](https://redis.io/commands/INCR), instead of implementing it ourselves:

https://github.com/jazzband/django-axes/blob/ac86d4b2139f632cee972e874984982a9628ab27/axes/handlers/cache.py#L100

Ref. #777.

**Comment by aleksihakli** [comment]
This would be a very nice improvement if we could implement it in a way that is supported by at least the most common cache backends.

It is worth considering through that the users utilizing the cache handler due to number or volume of requests or DDoS resistance will likely use a specific cache such as Memcached or Redis, which are likely to support atomic incrementation of the cache values.

The Django cache framework does provide a `cache.incr` method:

https://docs.djangoproject.com/en/3.2/topics/cache/#django.core.caches.cache.incr

This is atomic on select backends which support the atomic incrementation and have implemented the correct logic in the cache layer.

**Comment by aleksihakli** [comment]
Added `6.x` label for reference, can also be implemented in `5.x`.

**Comment by aleksihakli** [comment]
This should be implemented by #1048
