### ISSUE TITLE
Performance improvement: Use cache to store failed logins

### ISSUE THREAD

**Issue by andresriancho** [jazzband/django-axes#89]
Performance improvement: Use cache to store failed logins, SQL queries are slow. Django-axes should use Django's cache framework for storing failed logins.

For example, you guys could store keys with the format `axes-<hash>` where the hash is `md5(ip+ua)`. The data for that key should be the number of failed logins sent by that ip+ua and the timeout for the key is the `AXES_COOLOFF_TIME`

**Comment by jedie** [comment]
:+1: I was about to open the same improvement ;)

**Comment by camilonova** [comment]
I'll leave this open for anyone who want to elaborate a PR

**Comment by camilonova** [comment]
Seems @jorlugaqui wants to tackle this down.

**Comment by jorlugaqui** [comment]
Hi Guys,

I am back, I have started to work on this issue. Here my progress: https://github.com/jazzband/django-axes/pull/197.

There are a lot of pending tasks,  I just wanted to share my changes in order to receive feedback earlier so I can apply them while I am making progress. 

This PR is a work in progress. cc @camilonova

**Comment by camilonova** [comment]
Thank you. @jedie maybe wants to review the PR as well.

**Comment by jorlugaqui** [comment]
@camilonova Check my PR again please.

**Comment by camilonova** [comment]
I just merged the changes made by @jorlugaqui 

Thanks a lot for contributing.
